# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='id',
            field=models.SlugField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
