# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:50
from __future__ import unicode_literals

import camper.events.mixins
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('things', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('value_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('speed', 'Speed'), ('power', 'Power'), ('distance', 'Distance'), ('other', 'Other'), ('brightness', 'Brightness')], max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('json_path', models.CharField(default='$.value', max_length=128)),
                ('ttl_seconds', models.IntegerField(default=15)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_alive_state', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='things.Thing')),
            ],
            bases=(camper.events.mixins.EventEmitter, models.Model),
        ),
    ]
