# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0002_auto_20171211_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value_type',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('speed', 'Speed'), ('power', 'Power'), ('distance', 'Distance'), ('rotation', 'Rotation'), ('brightness', 'Brightness'), ('image', 'Image'), ('state', 'State'), ('other', 'Other')], max_length=32),
        ),
    ]
