# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('thing-value-changed', 'Thing value changed'), ('thing-alive-state-changed', 'Thing "alive" state changed')], max_length=32)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.SlugField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='InputChannel',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutputChannel',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('destination_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('json_path', models.CharField(default='$.value', max_length=128)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('date_last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('ttl_seconds', models.IntegerField(default=15)),
                ('value_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('speed', 'Speed'), ('power', 'Power'), ('distance', 'Distance'), ('other', 'Other'), ('brightness', 'Brightness')], max_length=32)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='channels.InputChannel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='value',
            unique_together=set([('id', 'channel')]),
        ),
    ]
