# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 09:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('values', '0003_auto_20171212_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBackend',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('telegram', 'Telegram')], max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='notifications.NotificationBackend')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backends', to='values.Value')),
            ],
        ),
    ]
