# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:50
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User


def create_admin(apps, schema):
    user = User(username='admin', email='admin@localhost', is_staff=True, is_superuser=True)
    user.set_password('admin')
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_admin)
    ]

