version: '2.1'
services:
    app:
        image: camper
        environment:
            DJANGO_SETTINGS_MODULE: camper.settings
            PYTHONUNBUFFERED: 0
        command: ./bin/entrypoint.sh server
        links:
            - postgres
            - redis
        ports:
            - 9090:9090
    worker:
        image: camper
        environment:
            DJANGO_SETTINGS_MODULE: camper.settings
            PYTHONUNBUFFERED: 0
        command: ./bin/entrypoint.sh worker
        links:
            - postgres
            - redis
    channels:
        image: camper
        environment:
            DJANGO_SETTINGS_MODULE: camper.settings
            PYTHONUNBUFFERED: 0
        command: ./bin/entrypoint.sh channels
        links:
            - postgres
            - redis
        ports:
            - 9080:9080
    frontend:
        image: camper-frontend
        command: npm run dev
        ports:
            - 9091:9091
        links:
            - app
    postgres:
        image: postgres:9
        environment:
            POSTGRES_USER: camper
            POSTGRES_PASSWORD: camper
            POSTGRES_DB: camper
    redis:
        image: redis

